#!/bin/bash
echo $$ >> /root/bindhelper.lock
OPC=$(dialog --backtitle "BindHelper 1.0" --stdout --menu "Select a function:" 0 0 0 "Zone Options" '' "Record Options" '' )
[[ $OPC == "Zone Options" ]] && /etc/bindhelper/bindhelper2.sh
[[ $OPC == "Record Options" ]] && /etc/bindhelper/menur.sh
[[ $? -ne "0" ]] &&  /etc/bindhelper/exit.sh
